version: '3'
  
networks:
  default:
    driver_opts:
      com.docker.network.bridge.name: tootsie0

services:
  db:
    # image: mysql:8
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: djangodb
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306
  
  adminer:
    image: adminer
    ports:
      - 8080:8080

  django:
    build: .
    command: ./startup.sh
    depends_on:
    - db
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
